import numpy as np


class ScenarioManager:
    """
    Generates Monte Carlo environmental scenarios and manages the simulation
    time axis for the degradation simulator.

    Scenarios are batched arrays of Temperature [K] and Relative Humidity [0-1]
    generated by sampling from a normal distribution centred on the base values.
    All computations use NumPy.
    """

    # Named climate presets used by batch scripts for reproducibility
    CLIMATE_PRESETS = {
        "temperate":  {"base_temp_k": 293.0, "temp_var": 3.0, "base_rh": 0.60, "rh_var": 0.05},
        "tropical":   {"base_temp_k": 308.0, "temp_var": 2.0, "base_rh": 0.85, "rh_var": 0.08},
        "cold":       {"base_temp_k": 275.0, "temp_var": 2.0, "base_rh": 0.50, "rh_var": 0.05},
        "hot_dry":    {"base_temp_k": 318.0, "temp_var": 4.0, "base_rh": 0.30, "rh_var": 0.05},
        "refrigerated":{"base_temp_k": 277.0,"temp_var": 1.0, "base_rh": 0.90, "rh_var": 0.03},
    }

    def __init__(self, time_horizon_days: float, dt_days: float = 1.0):
        """
        Parameters
        ----------
        time_horizon_days : float  Total simulation duration [days]
        dt_days           : float  Time step size [days]
        """
        if time_horizon_days <= 0:
            raise ValueError(f"time_horizon_days must be > 0, got {time_horizon_days}")
        if dt_days <= 0:
            raise ValueError(f"dt_days must be > 0, got {dt_days}")
        self.time_horizon = time_horizon_days
        self.dt = dt_days
        self.time_steps = int(time_horizon_days / dt_days)
        self.t_array = np.linspace(0, time_horizon_days, self.time_steps)

    def generate_scenarios(
        self,
        base_temp_k: float,
        temp_var: float,
        base_rh: float,
        rh_var: float,
        num_scenarios: int,
    ):
        """
        Generate batched Monte Carlo temperature and RH scenarios.

        Parameters
        ----------
        base_temp_k   : float  Mean temperature [K] — must be > 0
        temp_var      : float  Std deviation of temperature [K]
        base_rh       : float  Mean relative humidity [0-1]
        rh_var        : float  Std deviation of RH [0-1]
        num_scenarios : int    Number of independent Monte Carlo scenarios

        Returns
        -------
        temps : np.ndarray  Shape (num_scenarios, time_steps) [K]
        rhs   : np.ndarray  Shape (num_scenarios, time_steps) [0-1]
        """
        if base_temp_k <= 0:
            raise ValueError(f"base_temp_k must be > 0 K, got {base_temp_k}")
        if not 0.0 <= base_rh <= 1.0:
            raise ValueError(f"base_rh must be in [0, 1], got {base_rh}")

        temps = base_temp_k + temp_var * np.random.normal(
            size=(num_scenarios, self.time_steps)
        )
        temps = np.clip(temps, 1.0, None)  # Temperature must be > 0 K (Arrhenius)

        rh_raw = base_rh + rh_var * np.random.normal(
            size=(num_scenarios, self.time_steps)
        )
        rhs = np.clip(rh_raw, 0.0, 1.0)

        return temps, rhs

    def generate_climate_profile(self, climate: str, num_scenarios: int = 1):
        """
        Generate scenarios from a named climate preset.

        This is the method used by all standalone batch scripts for
        reproducible environmental conditions.

        Parameters
        ----------
        climate       : str  One of: 'temperate', 'tropical', 'cold',
                             'hot_dry', 'refrigerated'
        num_scenarios : int  Number of Monte Carlo realisations (default 1)

        Returns
        -------
        temps : np.ndarray  Shape (num_scenarios, time_steps) [K]
        rhs   : np.ndarray  Shape (num_scenarios, time_steps) [0-1]
        """
        if climate not in self.CLIMATE_PRESETS:
            valid = list(self.CLIMATE_PRESETS.keys())
            raise ValueError(
                f"Unknown climate preset '{climate}'. "
                f"Valid options: {valid}"
            )
        p = self.CLIMATE_PRESETS[climate]
        return self.generate_scenarios(
            base_temp_k=p["base_temp_k"],
            temp_var=p["temp_var"],
            base_rh=p["base_rh"],
            rh_var=p["rh_var"],
            num_scenarios=num_scenarios,
        )
